events {
    worker_connections   2000;

}


http {
	access_log /var/stdout;
	error_log /var/stderr;

	server {
		listen 8080;

		server_name  _;

		location / {
			try_files $uri $uri /index.html;
			root /var/www/html;
		}
	}
}

