apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-config
          subPath: nginx.conf
          mountPath: /etc/nginx/nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
